export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1>Layout root </h1>

        {/* esse h1 vai ser renderizado em todas as paginas pq ele esta dentro de um layout root */}
        {children}
      </body>
    </html>
  );
}
